### ISSUE TITLE
how to use package installer on vita 3.63?

### ISSUE THREAD

**Issue by fspabon** [SilicaAndPina/psvimgtools-frontend#10]
i have installed hidden applications on my vita but when i open package installer it says"An error occured" .For this reason, i can't install any pkg on my vita 3.63?
Somebody please help me!

**Comment by SilicaAndPina** [comment]
You click "OK" and then tap "start"

NOTE: Package installer Will Not Work On A Retail CEX Vita It Only Works On IDU/Demo Mode. 
Hackinformer seems to have found away around this but they are not sharing >_<
