### ISSUE TITLE
the skype app is not running on my  vita 3.63.

### ISSUE THREAD

**Issue by fspabon** [SilicaAndPina/psvimgtools-frontend#11]
i am trying to install skype on my vita but is nt running .What  should i do?
i cant understand anything .please help me!

**Comment by SilicaAndPina** [comment]
wat you mean by "Its not running"??

**Comment by SilicaAndPina** [comment]
its patched on 3.65 apparently.

**Comment by SilicaAndPina** [comment]
wait 3.63? hmm what is the problem here?
