### ISSUE TITLE
can't install ark-2

### ISSUE THREAD

**Issue by adamcirillo** [SilicaAndPina/psvimgtools-frontend#15]
When trying to install ark-2 get this error in the cmd window

Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1542, in __call__
  File "easyinstallers\ARK\chooseBackup.py", line 139, in <lambda>
    self.Button1.configure(command = lambda: patch(defs.getTitleID(self.backupList.get(ACTIVE))))
  File "easyinstallers\ARK\chooseBackup.py", line 63, in patch
    easyInstallers.close_window(root)
  File "easyInstallers.py", line 33, in close_window
  File "lib-tk\Tkinter.py", line 1865, in destroy
TclError: can't invoke "destroy" command:  application has been destroyed

also get error C2-12858-4 when trying to copy the game across and the ark save data shows as a corrupted data psp application tried with and without onemenu. Games I tried ape quest demo and Final Fantasty dissidia duodecim 012. Using psvimgtools-frontend 0.4 and qcma 0.4.1. also tried running it with and without admin rights.

**Comment by adamcirillo** [comment]
I managed to figure out what's wrong had to refresh qcma database before copying the ape quest demo across not sure if your program is meant to refresh the database automatically or not.

**Comment by SilicaAndPina** [comment]
For some reason the program says 
TclError: can't invoke "destroy" command: application has been destroyed
but AFAIK this doesnt affect anything 
no it doesnt auto refresh database (thats qcmas thing, enable it in settings)
