### ISSUE TITLE
failure whitelisting pstv 3.65

### ISSUE THREAD

**Issue by ltcyx** [SilicaAndPina/psvimgtools-frontend#19]
Trying to patch a factory-reset pstv version 3.65 with the whitelist mod ends with success, but whitelist is not installed.

Let me know if I can provide more info or help in any way.

**Comment by SilicaAndPina** [comment]
i dont have a pstv to acturally try whitelister on..

**Comment by ltcyx** [comment]
can I buy you one?

**Comment by SilicaAndPina** [comment]
i mean sure. if you want?

**Comment by ltcyx** [comment]
Sure. Are you in the US?

**Comment by SilicaAndPina** [comment]
NZ, but i have a US Add if needed.

**Comment by SilicaAndPina** [comment]
Sorry for not working on this as much as id like to, been working on 3.60 recently, um so whats teh deal with the whitelist? is it just not working for no reason?

**Comment by the-importer** [comment]
@ltcyx
Did you try backing up the internal memory card instead of your physical one and patching that up instead?

**Comment by SilicaAndPina** [comment]
hmm maybe i need to remove topics from app.db too?
