### ISSUE TITLE
what does molecular.cmbackup do?

### ISSUE THREAD

**Issue by fspabon** [SilicaAndPina/psvimgtools-frontend#20]
i have resently seen a video of silica about installing molecular shell  by psvimgtool. 
but when i open it ,it says"An error occured".
i cant understand  anything.

Somebody please help me!!!

**Comment by SilicaAndPina** [comment]
it does absolutely nothing. 
i made that video because so many ppl asked me to try installing 3.60 homebrew w psvimgtools ofc it wouldnt work but everyone asked me to do it anyway.. so i did.. >_> and it showed in the video it didnt work too xD
