### ISSUE TITLE
why did silica and pina made  the vidoe about vita downgrade 3.63 to 3.60?

### ISSUE THREAD

**Issue by fspabon** [SilicaAndPina/psvimgtools-frontend#21]
i have watched a video that 100% legit vita downgrade 3. 63 to3. 60.itride the webside henkaku 4.tk/downgrade.but this does not work.
what shoud i do know?

**Comment by SilicaAndPina** [comment]
henkaku4.tk is now testssite.sili.cf (BTW That video is fake)
