### ISSUE TITLE
Document that a `cmadir.txt` file must be created on macOS

### ISSUE THREAD

**Issue by leolobato** [SilicaAndPina/psvimgtools-frontend#23]
I've only realized the file must be created because the app was crashing on launch on macOS because of the missing file.

And still I'm not sure where it should be pointing at. Should it point to the `Applications / Backups` folder that is configured on QCMA?

**Comment by SilicaAndPina** [comment]
Strange.. its suppost to look at your QCMA Config file.. and read the "Applications / Backups" folder in qcma directly.. wonder whats wrong .. can u post full error?
