### ISSUE TITLE
Clone PSP buble doens't work

### ISSUE THREAD

**Issue by chronoss09** [SilicaAndPina/psvimgtools-frontend#24]
I make a test to clonning my psp game but it doesn't work, i get this error : 

"Cloning bubble..
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1542, in __call__
  File "easyinstallers\ClonePSP\clone.py", line 87, in <lambda>
    self.Button1.configure(command=lambda: clone_support.set(self.titleid.get(),
oldtitleid,account))
  File "easyinstallers\ClonePSP\clone_support.py", line 40, in set
    filedata = filedata.replace(oldTitleId, newTitleId)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 8: ordinal
not in range(128)"

**Comment by SilicaAndPina** [comment]
And exactly waht was the titleid u where trying to set?

**Comment by chronoss09** [comment]
CHRONO001 and other :p

**Comment by SilicaAndPina** [comment]
hmm windows 64.. ill try it later today and see if it works..

**Comment by SilicaAndPina** [comment]
Just tried it on windows 10 64-bit working 100% as intended..

**Comment by SilicaAndPina** [comment]
Fixed, the problem was me using mode 'w' instead of 'wb'

**Comment by Duhjoker** [comment]
Im having same problem with version 0.5.4. 

What does w and wb in the last post?

**Comment by SilicaAndPina** [comment]
'w' is write (characters must be ascii)
'wb' is write binary. (characters are represented in hex)
