### ISSUE TITLE
Nothing Work 0.5.1

### ISSUE THREAD

**Issue by MystikMan97130** [SilicaAndPina/psvimgtools-frontend#25]
with auto update and new install 
[CloneBubble.txt](https://github.com/SilicaAndPina/psvimgtools-frontend/files/1068088/CloneBubble.txt)
[EmuBubble.txt](https://github.com/SilicaAndPina/psvimgtools-frontend/files/1068089/EmuBubble.txt)
Windows 10 64Bits

**Comment by SilicaAndPina** [comment]
i think your installation is broken.. trying to run psvimg.exe (instead of psvimg-create.exe or psvimg-decrypt.exe), cant find easyinstallers, etc.

**Comment by SilicaAndPina** [comment]
hmm. are you on 64-bit or 32-bit? ima check if my installers work properly..

**Comment by MystikMan97130** [comment]
I try 64 and 32 bit same bug :/

**Comment by SilicaAndPina** [comment]
Ok, so for whatever reason. your system is refusing to run "psvimg-create" an "psvimg-extract" both of these are in the installation files (or atleast should-be). you could try downloading the original PSVIMGTOOLS (from yifan github.com/yifanlu/psvimgtools/releases) whatever it is for your OS, extract the files into the same folder "run.exe" and all the other installed files are (defaul%appdata%/psvimgools) 
see if that works. ima go check if theres something wrong w my installers or if its just you.

**Comment by MystikMan97130** [comment]
Clone works now but after i can't use tool 
[Aterclone.txt](https://github.com/SilicaAndPina/psvimgtools-frontend/files/1075144/Aterclone.txt)

PS Vita says me clone is corrupt

**Comment by SilicaAndPina** [comment]
hmm  no idea whats wrong w the bubble cloner (arrg i hate how nothing that works on linux works on windows!!!)

**Comment by MystikMan97130** [comment]
Yep only after. Programming is too random :/

**Comment by SilicaAndPina** [comment]
now for me on windows 10 i have no "clone" button in ClonePSP WTF

**Comment by SilicaAndPina** [comment]
Line 34 of EasyInstallers.ClonePSP.ChooseBackup:
root.iconbitmap(bitmap=defs.getWorkingDir()+'\icon.ico')

something wrong w the icon file??!?

**Comment by SilicaAndPina** [comment]
ok i just re-did my installers and stuff for v.0.5.1 :3 
re-download them and it should work fine
