### ISSUE TITLE
Ioe error error 22 when downloading VHBL to savedata

### ISSUE THREAD

**Issue by Samc1832** [SilicaAndPina/psvimgtools-frontend#27]
IOError: [Errno 22] invalid mode ('wb') or filename: 'D:/PSVita/EXTRACTED/PGAME/NPUH90024/game/ux0_pspemu_temp_game_PSP_GAME_NPUH90024/"

**Comment by Samc1832** [comment]
That is the code I get when download VHBL, any way to fix this?

**Comment by Samc1832** [comment]
Nvm, I solved it ,  it is because there is no psp game save

**Comment by SilicaAndPina** [comment]
resolved..
