### ISSUE TITLE
RemoveFeatured Dont Work on PS TV 3.65

### ISSUE THREAD

**Issue by Clannade** [SilicaAndPina/psvimgtools-frontend#28]
![psvimgtools-frontend](https://user-images.githubusercontent.com/30007283/27988263-3bce11c6-63f4-11e7-9f33-231981c2ece9.png)

PSVIMGTOOLS-FRONTEND V0.5.2, When I Select the Easy Installers and RemoveFeatured and Select the Backup, It Gives me that error :(

I Need Something more? Or I doing it something Bad?

One Thing I see: When I select the Backup, It's Says "Patch Whitelist" :O

**Comment by Clannade** [comment]
![psvimgtools-frontend](https://user-images.githubusercontent.com/30007283/27988293-d5aa4b8e-63f4-11e7-9e97-222e82f440ac.png)
This :O

**Comment by SilicaAndPina** [comment]
Patch whitelist is a bug, aside from that AFAIK Featured app is adding itself back in every time the backup gets restored in 3.65, theres a new method of doing it from what i remember..

**Comment by Clannade** [comment]
What Method? :O

**Comment by SilicaAndPina** [comment]
something w eboot.bin

**Comment by the-importer** [comment]
Seriously, by this point, I think SONY is just trolling us by keeping this shitty tab. It serves no purpose, the ads are like 3 years old!! SilicaAndPina, please, I'll give you $20 if you have this thing fixed for 3.65.

**Comment by SilicaAndPina** [comment]
im looking into it, i found a new way to remove the icon but it shows an error at startup for some reason . . . there must be a better way.
