### ISSUE TITLE
Various Bugs

### ISSUE THREAD

**Issue by chronoss09** [SilicaAndPina/psvimgtools-frontend#3]
Account Manager :
	Edit Account delete the actual account.

Resign PSP Game / PSVita for another account :
   PSP : Can't send the game to another account : couldn't copy some content items, the file is corrupt...
   Vita : I can send the game but error an launch : C0-11136-2

Hidden APP work well !
Tonight, i will test ARK or VHBL bubble !

ARK : error on the save ARK_123 instead of ARK_1234 and, i have this at the end : 
https://gyazo.com/fd93faa39f4d9aca68e2df9830c74e80

**Comment by SilicaAndPina** [comment]
I couldnt figure out what was wrong with ARK (but i allready had the correct savedata copied!) so your saying its removing the 4 on the savedata's name? huh
ill look into that

**Comment by chronoss09** [comment]
Yes, with the correct savedata, it work very well and good luck for the next version ?

**Comment by SilicaAndPina** [comment]
everything should be fixed in the next version 
except for the account mannager, i cant seem to get mine to just delete the backup when i press edit...

**Comment by SilicaAndPina** [comment]
opps i didnt mean to close it, its only meant to close once everything is fixed.

**Comment by chronoss09** [comment]
Ok, i will make some test with the new version 👍

**Comment by chronoss09** [comment]
Here my quick test : 

Installer x64
	white icone on desktop
	
Account manager
	always take just the last account

Edit account
	always delete the account
	
Select backup
	no title for backup
	https://gyazo.com/9443894d20c97fd28fdda62414568064

ARk and VHBL
	Samething, backup created in 3s and i have this error :
	https://gyazo.com/bf9d2d22946368ed7f40b7301ca0f43b

Save ARK and VHBL
	Fix 👍 

Voila !

**Comment by SilicaAndPina** [comment]
incorrect backup names..
possibly they use characters not supported by your computer?
or maybe PARAM.SFO is broken somehow lol this stuff works fine for me

ARK-2 
That error has nothing to do with ARK-2 xD that error is the error i get every 5 secs that doesnt do anything.
ARK Backup creation depends on the size of the PSP Game your patching.

**Comment by SilicaAndPina** [comment]
icon issues fixed in v0.2.1

**Comment by chronoss09** [comment]
thanks icon fix 👍 but not title of game, samething with the v0.2 :(

**Comment by SilicaAndPina** [comment]
Game title thing is weird lol code works fine on linux, only effects windows, and only PSP games?

**Comment by chronoss09** [comment]
Can you explain me why I have only the title ID for Ape Escape and not the name of game ?

It work now for all game (PSP and Vita) with the latest version, i can see the names of for all game but not only for Ape Espace :(

**Comment by SilicaAndPina** [comment]
I dont exactly know whats wrong with it i didnt really code the param.sfo reader i just got one from the internet 

System backups are what you get when you go into CM on the vita and have "backup" and "restore"
they backup most of ux0, and ur0 which leaves us with lots of possiblitys

**Comment by chronoss09** [comment]
Oki

**Comment by SilicaAndPina** [comment]
this is pretty much because i dont acturally know how param.sfo works.

**Comment by chronoss09** [comment]
👍

**Comment by SilicaAndPina** [comment]
ive tried param.sfo parsing on 6 different VM's with the exact same windows install and stuff
and it works on some and not others..
im legit confused
