### ISSUE TITLE
How to load PSM game ? 

### ISSUE THREAD

**Issue by Gamevita** [SilicaAndPina/psvimgtools-frontend#30]
Hello ! Sorry for issues spam xD 
I install PSM Games CMBACKUP recently but I have a problem my psvita says : PSM System is no activate and when I Activate PSM my psvita say DNS ERROR 
Is PSM game is Work in 3.65 ? or not working ? 
Good Night !

**Comment by SilicaAndPina** [comment]
Build a time machine
