### ISSUE TITLE
Only white window.

### ISSUE THREAD

**Issue by Kykz** [SilicaAndPina/psvimgtools-frontend#31]
Please have a time to read this issue.
whenever I press the account that I created in PSVImgtools it proceeds with a white blacnk window. My backed up games aren't there. I tried to use the latest version at first and it didn't work so i searched in youtube of how to use this tool and I've read in comment section that some of them are using older version. I also tried to use the older one but I failed to make it work. i've seen a lot of people are having the same problem just like mine.

thanks. I hope you you read this silica and pina.

**Comment by SilicaAndPina** [comment]
incorrect AID in your account probably..

**Comment by Kykz** [comment]
It's already okay now. it's on cma directory. some of people(including me)
when we start psvimgtools the cma directory is incorrect that's why we
always see a blank window. we should manually browse for the qcma back up
and never trust the auto browse.

**Comment by SilicaAndPina** [comment]
well 99% of the time, the auto find is correct ...
