### ISSUE TITLE
why psvimg tool frontend has stopped making?

### ISSUE THREAD

**Issue by fspabon** [SilicaAndPina/psvimgtools-frontend#32]
the last psvimg tool frontend was released one month ago. But after that it is stopped making.As per as siilica and pina's youtube channel silica,there is a video which says 'FAST reset' is coming soon in psvimg tool frontend for vita 3.65 .
But where it is?
it is stopped making!
hope you will read my issue and will give me my answer!!!

**Comment by SilicaAndPina** [comment]
i completly forgot about fastreset for 3.65 whoops.
nope not stopping development just couldnt think of anything to add
