### ISSUE TITLE
PSVIMGTOOLS crashing on start

### ISSUE THREAD

**Issue by Lollyn** [SilicaAndPina/psvimgtools-frontend#33]
![sem titulo](https://user-images.githubusercontent.com/30508373/28688359-1404152a-72e8-11e7-8300-f4a5c19d3317.png)

I'm currently receiveing this error when i try to execute the program :/

**Comment by SilicaAndPina** [comment]
hmmm try running '%appdata%\psvimgtools\run.exe m'?

**Comment by chronoss09** [comment]
can't open the program on W7 x64 :(

**Comment by SilicaAndPina** [comment]
i need more innfo.

**Comment by chronoss09** [comment]
x64 .exe : can't start the program
x64 with run.exe : the program start and auto close
Something with x32

**Comment by SilicaAndPina** [comment]
x64.exe?? wat

**Comment by chronoss09** [comment]
There is 2 version : the .exe and and .zip

**Comment by SilicaAndPina** [comment]
can u give me the error message plzz

**Comment by chronoss09** [comment]
I can't because the installer and the .zip file can't start...

**Comment by SilicaAndPina** [comment]
run it in CMD . . .

**Comment by SilicaAndPina** [comment]
hang on i think i found the problem..

**Comment by SilicaAndPina** [comment]
OK try downloading ti again from releases i fixed something

**Comment by chronoss09** [comment]
samething :(

**Comment by SilicaAndPina** [comment]
do CTRL + SHIFT + RIGHT CLICK and click open command window here.
then do %appdata%\psvimgtools-frontend\run

send me the error it gives. . .

**Comment by chronoss09** [comment]
"C:\ProgramData\psvimgtools-frontend>%ProgramData%\psvimgtools-frontend\run
Error loading Python DLL: C:\ProgramData\psvimgtools-frontend\python27.dll (erro
r code 193)"

**Comment by chronoss09** [comment]
v0.5.2 is on : %AppData\Roaming\psvimgtools-frontend
and
v0.5.3 here : C:\ProgramData\psvimgtools-frontend

Why the folder chanded ?

**Comment by the-importer** [comment]
Same here, v0.5.2 works, v0.5.3 doesn't.

**Comment by shonnonya** [comment]
So for now use .5.2?

**Comment by SilicaAndPina** [comment]
idk why the folder changed, its not meant to have (i set installpath to [userappdata]) which docs say is the appdata/roaming folder. . .

anyway i know that x64 doesnt work becuase something is wrong with the 64-bit compiler i will try to fix that later as well as the installdir, 

for now just use x32 ZIP file and extract to %appdata%/psvimgtools-frontend.

**Comment by the-importer** [comment]
@SilicaAndPina
Does 0.5.3 fix the Remove Featured tab issue?

**Comment by SilicaAndPina** [comment]
ok just fixed the installers everything *should* work

@the-importer no, not yet, that and fastreset are next update ^_^
