### ISSUE TITLE
psvimgtools problem when patching PSvita game 

### ISSUE THREAD

**Issue by dimis1974** [SilicaAndPina/psvimgtools-frontend#36]
i have the problem that showing in the picture 
![screen shot 2017-08-27 at 19 24 46](https://user-images.githubusercontent.com/31389089/29751955-b65c0d2c-8b5d-11e7-991e-53c5a8c41cfc.png)

**Comment by SilicaAndPina** [comment]
it doesnt like parallels desktop.. whats wrong with the MacOS version?

**Comment by dimis1974** [comment]
I don't how to use it on mac !!
Can you help me ?

Thanks!!

Στάλθηκε από το iPhone μου

28 Αυγ 2017, 8:59 πμ, ο/η Silica <notifications@github.com> έγραψε:

**Comment by SilicaAndPina** [comment]
its pretty easy, just download the mac version, unzip it. and double click "run"
(You will need to disable that thing that blocks stuff from unknown sources from running)

**Comment by dimis1974** [comment]
great!!! now i have this picture : is it ok ?

**Comment by dimis1974** [comment]
and also this

**Comment by SilicaAndPina** [comment]
those pictures are not working...
