### ISSUE TITLE
issue with macOS Sierra

### ISSUE THREAD

**Issue by bookintosh** [SilicaAndPina/psvimgtools-frontend#37]
Hi,

When I try to use your program, this is what I get : 

Last login: Thu Aug 31 11:27:21 on ttys000
imac-de-jerome:~ Bookintosh$ /Users/Bookintosh/Downloads/psvimgtools-frontend-macos/run ; exit;
/--PSVIMGTOOLS-FRONTEND v0.5.3--\ 
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for /Users/Bookintosh/PS Vita/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
/EXTRACTED Directory Does Not Exist, Creating!
Checking for EXTRACTED/APP
/EXTRACTED/APP Directory Does Not Exist, Creating!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Directory Does Not Exist, Creating!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Directory Does Not Exist, Creating!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Directory Does Not Exist, Creating!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Directory Does Not Exist, Creating!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: darwin
MacOS Is currently in BETA! Please report any bugs you may find.
Starting GUI
Looking For Backups In: /Users/Bookintosh/PS Vita/PGAME/4dbe21d210197b36
Found: 
Checking if allready extracted backup exists...
Nope! Extracting backup..
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1536, in __call__
  File "easyinstallers/VHBL/chooseBackupVHBL.py", line 138, in <lambda>
    self.Button1.configure(command = lambda: patch(defs.getTitleID(self.backupList.get(ACTIVE))))
  File "easyinstallers/VHBL/chooseBackupVHBL.py", line 52, in patch
    unsign_support.goUnsign(backup,CMA)
  File "unsign_support.py", line 86, in goUnsign
IOError: [Errno 21] Is a directory: 'keys/'

I use QCMA 0.4.1 for Yosemite because the version for Sierra doesn't seems to work
My Vita is recognized well with QCMA
I can Backup my game on my mac

**Comment by SilicaAndPina** [comment]
What? Keys/ is a directory? Thats the fucking point note the '/'? gosh macos. . .

**Comment by SilicaAndPina** [comment]
i might need to do // to make macos happy, who knows. or i could just store that info differently.

**Comment by SilicaAndPina** [comment]
will try // in the next update, if that dont work then i might migrate to a options.ini file or something like that.

**Comment by Alacard** [comment]
Seems like its not just a macOS im getting the same error on windows 10 creators update (at least it looks the same)

/--PSVIMGTOOLS-FRONTEND v0.5.3--\
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for D:/PSVita/Apps/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
Checking for EXTRACTED/APP
/EXTRACTED/APP Exists!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Exists!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Exists!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Exists!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Exists!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
.cmbackup=CmbackupFile
Executing: ftype CmbackupFile="D:\PSVita\Tools\run.exe"
CmbackupFile="D:\PSVita\Tools\run.exe"
Starting GUI
Looking For Backups In: D:/PSVita/Apps/SYSTEM/5bd9be81cc8fc170
Checking if allready extracted backup exists...
Nope! Extracting backup..
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1542, in __call__
  File "imgtools\easyinstallers\Whitelister\chooseBackup.py", line 159, in <lambda>
  File "imgtools\easyinstallers\Whitelister\chooseBackup.py", line 74, in patch
  File "imgtools\unsign_support.py", line 86, in goUnsign
IOError: [Errno 13] Permission denied: 'keys/'

**Comment by SilicaAndPina** [comment]
These are not the same error theres a big difference between permission denied and keys is a directory. . .

**Comment by vinz79** [comment]
I have exactly the same issue on windows 10 ... I tried to reinstall QCMA but no luck any additional suggestion ?

**Comment by iramcuba** [comment]
How would you remove registry keys from the qcma.

**Comment by SilicaAndPina** [comment]
HKLM/Software/Codestation/QCMA

something like that.

**Comment by SleepyDeJester** [comment]
sorry to bother you but can you help me i have some issue similar but it go like this : 
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for C:/Users/quang/OneDrive/Documents/PS Vita/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
Checking for EXTRACTED/APP
/EXTRACTED/APP Exists!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Exists!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Exists!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Exists!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Exists!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
Access is denied.
Error occurred while processing: .cmbackup.
Executing: ftype CmbackupFile="D:\PSV\psvimgtools-frontend-win64\run.exe"
Access is denied.
Error occurred while processing: CmbackupFile.
Starting GUI
AID: 6bbb7713a8e4255b
Account Name: SleepyDeJester
Downloading Key From: http://cma.henkaku.xyz/?aid=6bbb7713a8e4255b
CMA Key: 4d5dde29b1e81b2275eae459d2af23bc205fc1858d925cf7ed8f2a48cd535f04
Looking For Backups In: C:/Users/quang/OneDrive/Documents/PS Vita/PGAME/6bbb7713a8e4255b
Found: Petz Saddle Club Demo
Checking if allready extracted backup exists...
Nope! Extracting backup..
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1542, in __call__
  File "imgtools\easyinstallers\VHBL\chooseBackupVHBL.py", line 129, in <lambda>
  File "imgtools\easyinstallers\VHBL\chooseBackupVHBL.py", line 43, in patch
  File "imgtools\unsign_support.py", line 86, in goUnsign
IOError: [Errno 13] Permission denied: 'keys/'

**Comment by SleepyDeJester** [comment]
i found it in HKCU/Software/Codestation/QCMA, i tried to removed it, reinstalled it ,reconnected with my ps vita and tried to do everything again but i failed
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for C:/Users/quang/OneDrive/Documents/PS Vita/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
Checking for EXTRACTED/APP
/EXTRACTED/APP Exists!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Exists!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Exists!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Exists!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Exists!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
Access is denied.
Error occurred while processing: .cmbackup.
Executing: ftype CmbackupFile="D:\PSV\psvimgtools-frontend-win64\run.exe"
Access is denied.
Error occurred while processing: CmbackupFile.
Starting GUI

**Comment by SilicaAndPina** [comment]
issue is with 0.5.3, this version is no longer supported, please just use 0.5.2 instead.

**Comment by SilicaAndPina** [comment]
until i can fix 0.5.3 :)

**Comment by sossajigga** [comment]
Hi I kno I'm late I'm fairly new to ps vita trying to install the vhbl system but when I'm trying to patch it to the vita I get this: no such file or directory:

**Comment by SilicaAndPina** [comment]
Download psvimgtools from yifanlu into the sane directory
