### ISSUE TITLE
Account Manager issue

### ISSUE THREAD

**Issue by chronoss09** [SilicaAndPina/psvimgtools-frontend#4]
I have 4 account on my PC but the GUI takes just one account among the 4 when I press the "Auto" button of the "Add account" mode. It only takes the account that is in my Vita in 3.63, the rest of the accounts are in 3.60.

Can you tell me why ?

**Comment by SilicaAndPina** [comment]
The 'Auto' Button will only add The LAST account used with QCMA.

**Comment by chronoss09** [comment]
can you make it read all account in the next version ?

**Comment by SilicaAndPina** [comment]
No i cannot, i have no idea what the names of any of the other accounts are, QCMA only stores AID of other accounts and thats the only info it gives, i can read last used account name from windows registry or linux config files.
