### ISSUE TITLE
0.5.3 still crashes

### ISSUE THREAD

**Issue by the-importer** [SilicaAndPina/psvimgtools-frontend#40]
When running Run.exe, I quickly see a prompt Window opening and closing. Launching from a command prompt, I get this:

C:\Program Files\SilicaAndPina\psvimgtools-frontend>run
Traceback (most recent call last):
  File "imgtools\run.py", line 1, in <module>
  File "C:\users\silicaandpina\temp\pip-build-ys9cvo\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "imgtools\defs.py", line 9, in <module>
ImportError: No module named bplistlib
Failed to execute script run

**Comment by SilicaAndPina** [comment]
no module named bplistlib phew its something easy to fix . . .

**Comment by SilicaAndPina** [comment]
is your PC 64-bit im pretty sure that one will work . . . (i only tried 64 bit on my win10 lol)

**Comment by the-importer** [comment]
@SilicaAndPina 
Windows 10 64bit with Creative Update installed.

**Comment by SilicaAndPina** [comment]
noted, also seems my internet has decided to be terrible and wont let me upload anything could be awhile sorry.

**Comment by SilicaAndPina** [comment]
ok uploaded. try it now.

**Comment by the-importer** [comment]
@SilicaAndPina 
Same issue. Are you updating the setup or zip file of the 64bit version?

**Comment by SilicaAndPina** [comment]
b-both... why wont it work damn it. i jsut installed bplistlib.

**Comment by the-importer** [comment]
@SilicaAndPina 
Do I need to install this bplistlib thing as well or any other software to make it work?

**Comment by SilicaAndPina** [comment]
No only if u wanna compile / run from src
anyway i just updated it. . . try now?

**Comment by the-importer** [comment]
@SilicaAndPina 

Still not running (tried the zip file this time), but I get a different behavior:

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\the_importer>cd D:\Documents\Downloads\psvimgtools-frontend-win64

C:\Users\the_importer>run
'run' is not recognized as an internal or external command,
operable program or batch file.

D:\Documents\Downloads\psvimgtools-frontend-win64>run
/--PSVIMGTOOLS-FRONTEND v0.5.3--\
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
No Accounts Found, Auto-Generating From QCMA!
AID: 6dfef99edaf27d6b
Account Name:
Downloading Key From: http://cma.henkaku.xyz/?aid=6dfef99edaf27d6b
CMA Key: 65f40cdb6d5bf44bc6f93862836638038b082095928fbfb5a8f8dd15298c31c4
Traceback (most recent call last):
  File "imgtools\run.py", line 104, in <module>
  File "imgtools\defs.py", line 355, in autoAccount
IOError: [Errno 13] Permission denied: u'D:\\Documents\\Downloads\\psvimgtools-frontend-win64/keys/'
Failed to execute script run

**Comment by SilicaAndPina** [comment]
Permission denied, do you have access to 'D:\Documents\Downloads\psvimgtools-frontend-win64/keys/'?
if not try running as administrator

**Comment by the-importer** [comment]
@SilicaAndPina 
No go, even tried disabling the Windows Firewall just in case something need to go in or out.

**Comment by SilicaAndPina** [comment]
hmm interesting, could you try a different directory? maybe something on C:\.. .

**Comment by SilicaAndPina** [comment]
i just tried it on windows 10 64-bit with the installer and that worked. . . >_> oh another possiblity, is that the file is open in another program . . . i guess.

**Comment by the-importer** [comment]
OK, result time. I rebooted my main PC just in case, problem persists.

I tried it on my Surface Pro Win10 64bit with Creative Update after installing the same version of QCMA, and it works. Compare what it does in both command prompts:

--------------WORKS----------------
/--PSVIMGTOOLS-FRONTEND v0.5.3--\
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for C:/Users/NickG/Documents/PS Vita/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
Checking for EXTRACTED/APP
/EXTRACTED/APP Exists!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Exists!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Exists!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Exists!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Exists!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
Access is denied.
Error occurred while processing: .cmbackup.
Executing: ftype CmbackupFile="C:\Users\NickG\Downloads\psvimgtools-frontend-win64\run.exe"
Access is denied.
Error occurred while processing: CmbackupFile.
Starting GUI

-----------DOESN’T WORKS-------------
/--PSVIMGTOOLS-FRONTEND v0.5.3--\
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
No Accounts Found, Auto-Generating From QCMA!
AID: 6dfef99edaf27d6b
Account Name:
Downloading Key From: http://cma.henkaku.xyz/?aid=6dfef99edaf27d6b
CMA Key: 65f40cdb6d5bf44bc6f93862836638038b082095928fbfb5a8f8dd15298c31c4
Traceback (most recent call last):
  File "imgtools\run.py", line 104, in <module>
  File "imgtools\defs.py", line 355, in autoAccount
IOError: [Errno 13] Permission denied: u'D:\\psvimgtools/keys/'
Failed to execute script run
 
Both computers were formatted and Windows 10 (pre-Creative update) was installed from scratch. Sure, my main PC has a bit more programs than my Surface Pro (SQL 2008 R2 Express for example), but not that many. Also, this begs the question, what did you change from 0.5.2 to 0.5.3 that would cause this? Could the fact that I ran 0.5.2 prior to 0.5.3 be the issue, could some files or registry key from the previous version still be in my main PC?

**Comment by SilicaAndPina** [comment]
PSVIMGTOOLS-FRONTEND does not store registry keys, it does everything via config files (registry keys are annoying AF if u wanna make an app that works on all OS'es)

for whatever reason  its being denied access to D:\psvimgtools/keys/ you could try deleting that folder that may help . . .

**Comment by the-importer** [comment]
@SilicaAndPina 
Any idea why PSVIMGTOOLS can't find my account on my main PC Vs on my Surface Pro (No Accounts Found, Auto-Generating From QCMA!)?

**Comment by SilicaAndPina** [comment]
Because its trying to read it from keys/

**Comment by SilicaAndPina** [comment]
theres account data allredy saved so its just trying to read that rather than getting it from QCMA's configs

**Comment by the-importer** [comment]
OK, got it working. I suspected that this was a QCMA issue since it doesn't work at all without a valid profile. I uninstalled the QCMA, removed registry keys tied to it (settings and all), reinstalled, re-linked my PSTV to it and now it works just fine. 

The issue was either old QCMA configs or a question of re-linking your Vita/PSTV with QCMA, not sure which one, but it's passed 2:00 AM here, I'm not being paid to do this and I'm suppose to be on vacation meaning that I'm not suppose to be doing this trouble shooting shit :P

Later

**Comment by SilicaAndPina** [comment]
you found the QCMA registry keys without a registry monitor.. gosh thats better than what i did//

**Comment by the-importer** [comment]
I just did a search for QCMA in regedit cause CCleaner couldn't find shit.

**Comment by SilicaAndPina** [comment]
o why didnt i think of that. . .  >_>

anyway if u cant tell, psvimgtools-fe reads those reg keys to get the account info and stuff. . .

**Comment by the-importer** [comment]
Figured as much. On my Surface Pro, I didn't install QCMA and psvimgtools didn't too far without it. Anway,  best of luck with the next update, my reward still stands, if you get rid of the annoying Featured Tab, I'll donate $20 to your Paypal account.

Good night

**Comment by SilicaAndPina** [comment]
good night ^_^

ima work on featured app and some other things. . .

**Comment by leo2997** [comment]
@SilicaAndPina 
hi im new to this stuff im trying to intall vhbl on my vita FW3.65 im using psvimgtool v0.5.3 i did all the other instructions on this site https://hackinformer.com/2017/04/28/psvita-install-vhbl-bubble-fw3-65/

but im getting an error when i press the easy installer
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1541, in __call__
  File "main_support.py", line 29, in esyInstall
  File "C:\py64\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "easyInstallers.py", line 18, in <module>
  File "C:\py64\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "easyInstallers_support.py", line 8, in <module>
ImportError: No module named easyinstallers.Whitelister.main

thank you i hope you can also help me

**Comment by donbakala** [comment]
Hi @leo2997 .
i resolved the problem by downloading older version.
Hope it helps.
