### ISSUE TITLE
Can't actually use theses tools

### ISSUE THREAD

**Issue by DarkSoulsJunkie** [SilicaAndPina/psvimgtools-frontend#41]
So I'm using the Windows 32-Bit version of this. I've tried both the .zip & installer versions & each time I activate the run.exe all I get is the black screen with text on it, not the actual front end with the Easy Installer button on it. I'm trying to use this to install VHBL to my Vita & I can't get to the screen that lets me change a PSP bubble into a VHBL bubble. I might not fully understand what I'm trying to do, but it's getting annoying. Please Help

**Comment by SilicaAndPina** [comment]
this is not acturally enough information, id need to know what error is coming up from the run.exe, you should be able to find this simply by running run.exe in CMD, (ctrl+shift+right click on the install folder, and do open command window here and type 'run')

**Comment by DarkSoulsJunkie** [comment]
I've tried that now. It says 'run' isn't recognized as an internal or external command, operable program or batch file.

**Comment by DarkSoulsJunkie** [comment]
Although, I do believe I'm suffering from a different problem. While the computers says that, I can still activate run.exe. So I did that and it just sat there when it mentioned downloading a key from Henkaku. I let it sit there for a while & it eventually said it couldn't connect to the site & aquire my CMA Key. Somewhere in here, an issue is occurring, I just don't know what it is

**Comment by SilicaAndPina** [comment]
You dont have access to cma.henkaku.xyz. without this theres no way you can get your cmakey. without your cmakey you cannot use psvimgtools. >->
