### ISSUE TITLE
3.65 Occur error when install VHBL with psp demo

### ISSUE THREAD

**Issue by blackwave852** [SilicaAndPina/psvimgtools-frontend#43]
The "run.exe" occurs " IOError: [Errno 13] Permission denied: 'keys/' " when I choose the PSP demo "Locoroco" to and click the button "patch W VHBL", I don't know whats going on and hope you can help me. Thanks a lot.

**Comment by GitHubyoyo** [comment]
you can try other demo,ex"petz ........."
