### ISSUE TITLE
keys directory error

### ISSUE THREAD

**Issue by devjsullivan** [SilicaAndPina/psvimgtools-frontend#45]
If I rename the directory, it barks at me that it doesn't exist, otherwise it barks that it's a directory.

Last login: Tue Sep 12 23:27:53 on ttys000
/Users/kevinsullivan/Downloads/psvimgtools-frontend-macos\ \(1\)/run ; exit;
Kevins-MacBook:~ kevinsullivan$ /Users/kevinsullivan/Downloads/psvimgtools-frontend-macos\ \(1\)/run ; exit;
/--PSVIMGTOOLS-FRONTEND v0.5.3--\ 
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for /Users/kevinsullivan/Documents/PS Vita/EXTRACTED/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
/EXTRACTED Directory Does Not Exist, Creating!
Checking for EXTRACTED/APP
/EXTRACTED/APP Directory Does Not Exist, Creating!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Directory Does Not Exist, Creating!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Directory Does Not Exist, Creating!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Directory Does Not Exist, Creating!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Directory Does Not Exist, Creating!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: darwin
MacOS Is currently in BETA! Please report any bugs you may find.
Starting GUI
Looking For Backups In: /Users/kevinsullivan/Documents/PS Vita/EXTRACTED/PGAME/eb0c53a11d4c2e62
Found: Petz Saddle Club Demo
Checking if allready extracted backup exists...
Nope! Extracting backup..
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1536, in __call__
  File "easyinstallers/VHBL/chooseBackupVHBL.py", line 138, in <lambda>
    self.Button1.configure(command = lambda: patch(defs.getTitleID(self.backupList.get(ACTIVE))))
  File "easyinstallers/VHBL/chooseBackupVHBL.py", line 52, in patch
    unsign_support.goUnsign(backup,CMA)
  File "unsign_support.py", line 86, in goUnsign
IOError: [Errno 21] Is a directory: 'keys/'

**Comment by SleepyDeJester** [comment]
You should go the older version, i get the same error like you and i try older version and thankfully it works

**Comment by devjsullivan** [comment]
yep that's what I did thanks :)

**Comment by SleepyDeJester** [comment]
No problem, kinda frustrated with that but thanks god it works
