### ISSUE TITLE
Permission denied: 'keys/'

### ISSUE THREAD

**Issue by deathismario** [SilicaAndPina/psvimgtools-frontend#46]
What's wrong? Why won't it work? Can anyone help me?

/--PSVIMGTOOLS-FRONTEND v0.5.3--\
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for C:/Users/d3ath/Documents/PS Vita/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
Checking for EXTRACTED/APP
/EXTRACTED/APP Exists!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Exists!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Exists!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Exists!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Exists!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
Access is denied.
Error occurred while processing: .cmbackup.
Executing: ftype CmbackupFile="C:\Users\d3ath\AppData\Roaming\psvimgtools-frontend\run.exe"
Access is denied.
Error occurred while processing: CmbackupFile.
Starting GUI
Looking For Backups In: C:/Users/d3ath/Documents/PS Vita/PGAME/63b36ac9f8e72252
Found: LocoRocoΓäó-Midnight Carnival-
Checking if allready extracted backup exists...
Nope! Extracting backup..
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1542, in __call__
  File "imgtools\easyinstallers\ARK\chooseBackup.py", line 139, in <lambda>
  File "imgtools\easyinstallers\ARK\chooseBackup.py", line 48, in patch
  File "imgtools\unsign_support.py", line 86, in goUnsign
IOError: [Errno 13] Permission denied: 'keys/'

**Comment by deathismario** [comment]
I've tried other versions, 64 and 32 bit, they're in appdata, nothing.

**Comment by stuartpbuckley** [comment]
I am getting a similar error. Used compatibility mode, launched using Admin rights. I am not using ARK as this is patched in 3.65 but trying to use VHBL. does anyone have the answer?

**Comment by zilrian** [comment]
I am in the same state.
What should I do?
Help. please.
