### ISSUE TITLE
Why did you close all of the issues, did you solve everything?

### ISSUE THREAD

**Issue by the-importer** [SilicaAndPina/psvimgtools-frontend#48]
-topic-

**Comment by SilicaAndPina** [comment]
no responses for like 30+ days lol

**Comment by the-importer** [comment]
Any progress in getting rid of the PSTV's featured tab in 3.65

**Comment by SilicaAndPina** [comment]
have not looked into it, what exactly is wrong?

**Comment by the-importer** [comment]
It's one of the issues that you removed lol
The PSTV featured tab removal option doesn't work in 3.65.

**Comment by SilicaAndPina** [comment]
try : https://github.com/SilicaAndPina/psvimgtools-frontend/releases/v0.5.3
