### ISSUE TITLE
Problem with Extracting/Packing

### ISSUE THREAD

**Issue by Ghirahimslayer** [SilicaAndPina/psvimgtools-frontend#49]
Whenever I take a Backup, extract it, resign and pack it, and restore it to my vita, All my themes give the Error code (C1-2738-0) and all my downloaded Applications give the code (C0-11136-2). If there is anything I'm doing wrong or if you know a way around this/to fix this please let me know. Also let me know if you need me to elaborate on anything

**Comment by SilicaAndPina** [comment]
Custom themes where patched in 3.65+

**Comment by SilicaAndPina** [comment]
Development stopped.
