### ISSUE TITLE
Application doesnt open for some people

### ISSUE THREAD

**Issue by icamont** [SilicaAndPina/psvimgtools-frontend#5]
when i try to open the run file, it closes immediately, theres no pop up that says easy installer and what not..

**Comment by SilicaAndPina** [comment]
Try the new version i just released..

**Comment by ashpro1212** [comment]
I tried to run run.exe but closed immediately and no easy installer appears on the newer version

**Comment by eacikalin** [comment]
Select backup list is empty while i was trying to load. I think it cannot find the backups. Has anyone experienced this kind of issue?


![image](https://cloud.githubusercontent.com/assets/26920710/24717622/64a68174-1a33-11e7-8bd0-f5e2ca82d2c0.png)

**Comment by SilicaAndPina** [comment]
Try not using windows 95..

**Comment by eacikalin** [comment]
This is actually windows7 32bit version.

**Comment by CelesteBlue-dev** [comment]
Ahah ROFL eacikalin is right it's Win 7 32bits (starter edition).
So Silica you should verify if the win 32 bits only mode is working...

**Comment by SilicaAndPina** [comment]
Well most obvious thing I can think of is check cmadir. txt

**Comment by SilicaAndPina** [comment]
From the screenshot it looks like it's looking in /PGAME for backups which obviously doesn't exist because windows has drive letters lol

**Comment by eacikalin** [comment]
I have tried, however i think, something is going wrong. :(


![image](https://cloud.githubusercontent.com/assets/26920710/24976946/b69e28ae-1fcb-11e7-9a9c-9198c068d266.png)

**Comment by SilicaAndPina** [comment]
It doesnt like your windows username for having the I with the 2 dots on the top..

**Comment by eacikalin** [comment]
I have changed the username however it seems not enough, i think that i need to turn the windows completely English version, because i use Turkish version. Hence it causes incompability with your program and gives unicode error I think.

**Comment by eacikalin** [comment]
Despite I' have changed to windows language to "English" the program keeps saying "unicode error", it may be related to problem with psvimgtools 32 bit version. I will try it on another pc running windows 8 running 64 bit windows

**Comment by eacikalin** [comment]
I have tried in 64bit windows 7 and installed 64 bit version of psvimagetools and result was succesfull. Thank you for your program and easy installer which is very convenient. Great job:)
