### ISSUE TITLE
PSVIMGTOOL 0.5.2 HELP PLZ

### ISSUE THREAD

**Issue by miha270404** [SilicaAndPina/psvimgtools-frontend#54]
When i open PSVIMGTOOL it shows this, and just off/ ( download a zip file (x64 system))
![default](https://user-images.githubusercontent.com/33307091/32310588-421f612a-bfb5-11e7-9183-f717f7dfcf38.JPG)

**Comment by miha270404** [comment]
So i downoad PSVIMGTOOL v0.3 and its work< but when i try to patch it show me an error
![default](https://user-images.githubusercontent.com/33307091/32315441-f1e59616-bfcd-11e7-8412-edff82cf2db5.JPG)

**Comment by SilicaAndPina** [comment]
with 0.5.2 its just having trouble accessing http://cma.henkaku.xyz. do you have access to that on your network?

**Comment by SilicaAndPina** [comment]
Development stopped.
