### ISSUE TITLE
Can't Whitelist PSTV 3.65

### ISSUE THREAD

**Issue by RandomAnimeGamer** [SilicaAndPina/psvimgtools-frontend#55]
There was an issue previously from May that got locked. Basically, I'm having the same issue. PSVImgTools says it's successful, but restoring it on PSTV doesn't actually whitelist.

I noticed that an error "Could not find the application" appears at the end of restoring before it finishes the last few MB and restarts my PSTV to rebuild its database.

Is there something I'm doing wrong here? Is there any fix to this? Is this at least a known issue that's been reproduced?

**Comment by SilicaAndPina** [comment]
hm "could not find the application" ? interesting...
im trying to work out whats causing this but honestly it seems sony changed some shit

**Comment by RandomAnimeGamer** [comment]
Are you actually testing it on a 3.65 Vita TV or using HENkaku? I'm on 3.65 OFW. The apps I tried specifically were Dengeki Bunko: Fighting Climax and Naruto Shippuden: Ultimate Ninja Impact if you want to give it a go.

**Comment by SilicaAndPina** [comment]
im testing it on henkaku, xD its all i have and i aint updating that shit

**Comment by RandomAnimeGamer** [comment]
Dude, the Vita tv is literally $60 usd new

**Comment by SilicaAndPina** [comment]
doesnt mean im gonna spend money on it.
why would i? i provide this stuff for free. i make nothing from it.
i allready have a 3.65 psvita i have no reason to get a pstv 3.65.

also i left the scene. so yea even more reason why i wont

**Comment by RandomAnimeGamer** [comment]
I never said you had to spend money on it nor did I say you should.

The fact that you're getting overly defensive over this only shows just how little the PS Vita hacking community knows about actual hacking, save for the few people that made Henkaku.

You left the scene? Great, I don't care. When people have the type of attitude that most PS Vita hackers have towards their own scene, it might as well not even exist anymore.

And no, it's not the Vita's fault that it has over-the-top security, it's your guys' fault for not understanding why you're even here or how to do things properly. One day in the VitaHacks Discord proved this for me.
