### ISSUE TITLE
It does not detect the backup!

### ISSUE THREAD

**Issue by mordoz** [SilicaAndPina/psvimgtools-frontend#60]
When i try to install VHBL, it simply does not show the backups necessary for me to install it. Help! (It is Windows 10 64 bit)

CMA DIR is blank, and when i click in AUTO it does not do anything
![0](https://user-images.githubusercontent.com/34993654/34465419-b6ee71f4-eea3-11e7-9528-758c48350a97.png)
![1](https://user-images.githubusercontent.com/34993654/34465420-b9013328-eea3-11e7-873a-43be5174a012.png)

**Comment by dotmaik1** [comment]
I'm on the same scenario, please help

**Comment by SilicaAndPina** [comment]
You said cma dir was blank and auto dont work so theres your problem, set it manually
