### ISSUE TITLE
While running

### ISSUE THREAD

**Issue by EremesKagu** [SilicaAndPina/psvimgtools-frontend#62]
So once it's running and I install and select my account there isn't anything showing to select to patch it to no matter how I change the cma

**Comment by SilicaAndPina** [comment]
can i see the console?

**Comment by SilicaAndPina** [comment]
GIVE ME CONSOLE ENOUGH WITH THESE 1 COMMENT ISSUES THAT NO ONE WANTS TO BE HELPFULL IN >__>
