### ISSUE TITLE
Couldn't select backups

### ISSUE THREAD

**Issue by Sulislit** [SilicaAndPina/psvimgtools-frontend#63]
help me !!
EasyInstallers wont regconize my game tho i had it in PGAME ,here is a pic
![jjj](https://user-images.githubusercontent.com/35618884/35179517-73404ff6-fdce-11e7-854c-b6174e0222f5.png)

**Comment by SilicaAndPina** [comment]
Looking for backups in PS Vita/PGAME/AID/PGAME/AID -_-

Please set your cmadir to The "PS Vita" folder.
