### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by Makii99** [SilicaAndPina/psvimgtools-frontend#66]
Whenever i try to run "run.exe" it pops up a command prompt, And exits. thats all. its too fast for my eyes to see much but all it does it look for updates is all i can tell.

**Comment by SilicaAndPina** [comment]
probably an issue with NPS since they decided it was a great idea to change there URL. it will be fixed in next verison but first just run it with argument "noKeyUpdate"?

**Comment by SilicaAndPina** [comment]
Please try version 1.5.4

**Comment by SilicaAndPina** [comment]
no response? .-. closed for inactivity, feel free to open it again if you need to
