### ISSUE TITLE
I can't lanch the psvimgtools-fronted

### ISSUE THREAD

**Issue by kostaszaxos050** [SilicaAndPina/psvimgtools-frontend#67]
Here is a screenshot before it completely closes can you help me? https://www.dropbox.com/s/y7jlef8xo51y5ra/Screenshot_244.png?dl=0

**Comment by SilicaAndPina** [comment]
.encode("UTF-8") on filepaths?

**Comment by kostaszaxos050** [comment]
If I understand right and this is a file that I must have. I don't have it

**Comment by chronoss09** [comment]
The latest version does not start :(

**Comment by SilicaAndPina** [comment]
issue is you have non-unicode characters in your windows username or somewhere in the path where psvimgtools is stored. ill fix it in the next build ..

**Comment by SilicaAndPina** [comment]
it definately works on windows i acturally programmed it on windows this time because my linux pc was broken ...

**Comment by SilicaAndPina** [comment]
this is a duplicate of #64 please put all further discussion there.
