### ISSUE TITLE
VitaShell backup does not appear on Vita

### ISSUE THREAD

**Issue by dothackjhe** [SilicaAndPina/psvimgtools-frontend#69]
I'm not sure what is causing this issue. Apparently, some people such as myself, am having trouble fetching the VitaShell backup which PSVIMGTOOLS would have made for it.

Surprisingly enough, the folder for it and the actual files are there.

**Comment by SilicaAndPina** [comment]
Is this actually an issue or just people not knowing how to use QCMA/PSVIMGTOOLS-FRONTEND

**Comment by dothackjhe** [comment]
Honestly, I'm guessing it's the latter which I kind of realized yesterday.

I think I'm having trouble on the last part where CMA/QCMA could not pinpoint the VitaShell files which PSVIMGTOOLS would have generated according to my account. Can you help on this?

**Comment by SilicaAndPina** [comment]
Have you tried refreshing qcma database?

**Comment by dothackjhe** [comment]
Yes, always have.

I think QCMA is detecting an old account in my Vita, essentially a dummy account, instead of my main which I am now using with it. Is there a workaround to this?

**Comment by SilicaAndPina** [comment]
Uh hmmmm it should detect whatever account you connect to the vita with

**Comment by dothackjhe** [comment]
Is that feature fool-proof? Cause, really, I'm using a different account now and yet it detects an old. I tried adding this new account with an AID pointing to VitaShell, yet I'm getting the same problem: the files would not appear on the Vita to be copied into it.

**Comment by SilicaAndPina** [comment]
Do you see the pop up like "connected to your user PSVITA"

**Comment by dothackjhe** [comment]
Yes, via CMA's tray.

**Comment by SilicaAndPina** [comment]
Is that account correct

**Comment by dothackjhe** [comment]
By the way, I could connect just fine with CMA, but on with QCMA for some reason. 

Also, I noticed that the account which PSVIMGTOOLS detects is that one from QCMA which was my old account i.e. incorrect.

**Comment by SilicaAndPina** [comment]
Oh you'll need to add an account manually and set paths manually for Sony CMA its not really supported that well

**Comment by SilicaAndPina** [comment]
Especially if u have qcma installed currently

**Comment by dothackjhe** [comment]
Is it a requirement that I get to have QCMA connect with my Vita first? I'm especially concerned about my device not connecting to the PC through it.

**Comment by SilicaAndPina** [comment]
Probably because the driver for qcma is known to interference with the one from official CMA thus making it not connect.

**Comment by dothackjhe** [comment]
So, basically, this is the procedure I'm following: https://gbatemp.net/threads/restore-vitashell-on-henkaku-3-65.498636/

Anything you may add from these steps that will ultimately make the process work?

**Comment by SilicaAndPina** [comment]
Why did he say download CMA if he never even uses it..

**Comment by dothackjhe** [comment]
So there's something wrong with the idea of running both QCMA and CMA simultaneously or running CMA alone with the aforementioned procedure?

**Comment by SilicaAndPina** [comment]
Running both at the same time is asking for troubles.

**Comment by dothackjhe** [comment]
Does this mean that CMA and PSVIMGTOOLS alone are enough for the process?

**Comment by SilicaAndPina** [comment]
Yep :)

**Comment by SilicaAndPina** [comment]
I'd recommend trying with qcma software is more designed for it.

**Comment by dothackjhe** [comment]
Noted, thanks.

**Comment by dothackjhe** [comment]
QCMA + PSVIMGTOOLS really does work. I literally had to uninstall CMA in the process. Thanks for the assistance @SilicaAndPina

**Comment by dothackjhe** [comment]
Just another question @SilicaAndPina. Is PSVIMGTOOLS now designed to fetch for the installation files of VitaShell 1.83 instead of 1.82? 

Updating VitaShell with its updated VPK does not seem to be the right way about it. But, having lost MolecularShell, I have no other option but to install VitaShell as a 1.83. Is this possible?

**Comment by SilicaAndPina** [comment]
now using vitashell 1.9 in psvimgtools-frontend 0.6.1 (auto updater acturally works on this ver)

**Comment by SilicaAndPina** [comment]
o also, ive heard people have had to manually remove the driver installed by sony's CMA when installing qcma because sometimes they would conflict with eachother (blame sony for not removing everything @ uninstall) not sure if that got fixed. . . annyway since this issue is resolved.. and wasnt really an issue, Closeed
