### ISSUE TITLE
Error PSTV whitelist 3.67

### ISSUE THREAD

**Issue by noxeon** [SilicaAndPina/psvimgtools-frontend#71]
I'm getting "OperationalError: trigger CHANGE_CATEGORY_GPC already exists" when I try to whitelist patch my 3.67 backup.

![capture](https://user-images.githubusercontent.com/37372908/37406161-687c88b6-278e-11e8-921d-f5b90e83ec33.PNG)

Any ideas what the problem might be?

**Comment by SilicaAndPina** [comment]
possibly its allready been whitelisted?

**Comment by noxeon** [comment]
Yes it was whitelisted long time ago (on 3.60), since it has been updated few times now I thought that it would be wiped off completely. So I formatted and tried again, it works after I redownload Vita games but doesn't work on PSP games unfortunately. Final Fantasy 1-4 (PSP) don't work on PSTV with EU account, any way to get them to work on 3.67?

**Comment by SilicaAndPina** [comment]
No, only if you can somehow access list_launch_emu.dat.

**Comment by Diksta33** [comment]
Yes, it's probably worth noting that this whitelist doesn't allow "ALL" games to work, certainly any PSP EU game I have tried totally fails to load.  Is there a working hack out there for EU games like Tactics Ogre or FF Tactics?
