### ISSUE TITLE
Error #2 PSTV whitelist 3.67

### ISSUE THREAD

**Issue by paulexdias** [SilicaAndPina/psvimgtools-frontend#72]
I´ve noticed the otehr day when I made a restore of a backup that contained the following games:
Wipeout 2048
Uncharted golden abyss
Sine Mora
and
Treasures of Montezuma blitz

all games that need are blacklisted, well only uncharted and wipeout became whitelist
treasures of montezuma blitz and sine mora weren't.

and when I was restoring I got several times an error message saying that the application is not available. so when the restore was finished I had to close more than 20 pop up messages.

**Comment by SilicaAndPina** [comment]
this is because we can only do Whitelist v2 via CMA, (app.db crap) but not whitelist v1 (ur0:launch crap)

**Comment by paulexdias** [comment]
so which is on the app whitelist v2? how can I manage to do whitelist v1 on firmware 3.67 is it possible?

**Comment by SilicaAndPina** [comment]
no, the vita doesnt backup what is needed to do that

**Comment by paulexdias** [comment]
Little question not related to this, since I don't know where I could ask you this, but can you with PDEL-1001 install psn games and retail games overwriting the firmware?

I'm asking this because I would like to play on a tv and because it has hdmi out.

thanks for answering

**Comment by SilicaAndPina** [comment]
PDEL can play retail games yes.
