### ISSUE TITLE
decrypt savedata ability

### ISSUE THREAD

**Issue by shirokuuhaku** [SilicaAndPina/psvimgtools-frontend#73]
excuse me
can I use this tool to decrypt psvita's savedata for vita-savemgr?
 
I tried to backup my psvita"s savedata with the vita-savemgr
,but the game get a c2-14646-1 error
when I delete the sealedkey,there is no more c2-14646-1 error. but no savedata dected in the game also i can't backup so I try to do it on pc.

If it can't, Can you make a possibility to do it?

Thanks.

**Comment by SilicaAndPina** [comment]
you can probably ?

**Comment by shirokuuhaku** [comment]
I'm sorry for that.
might there can be a way to decrypt psvita's savedata on the pc that without open the game soft on psVita
Maidump's game savedata might have a terrible bug,I got that error for some times, everytime 2 or more game's data gone
If you are busy,please dont care this case,that just my selfish

**Comment by SilicaAndPina** [comment]
yea its possible w psvpfstools.
