### ISSUE TITLE
linux: ioerror: Is a directory: '/psvimg/keys/'

### ISSUE THREAD

**Issue by ivdok** [SilicaAndPina/psvimgtools-frontend#75]
```[ivdok@LENOVO-20255 psvimg]$ ./run
/--PSVIMGTOOLS-FRONTEND v0.6-\ 
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Extracting CMBackup File
Checking for updates
Could Not Connect, Skipping Update Check.
Updating: /home/ivdok/Downloads/psvimg/keydb.ini
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
No Accounts Found, Auto-Generating From QCMA!
AID: fac68fa92713f209
Account Name: 
Downloading Key From: http://cma.henkaku.xyz/?aid=fac68fa92713f209
CMA Key: b3f1d5e616eba6a3bf7717aa5bfa97220beb15ef8ff6ff69222ecd5ba8af6d5b
Traceback (most recent call last):
  File "run.py", line 115, in <module>
  File "defs.py", line 360, in autoAccount
IOError: [Errno 21] Is a directory: '/home/ivdok/Downloads/psvimg/keys/'
[16511] Failed to execute script run
```
Judging by defs.py:360, it expects that this folder has any account pulled from PSV. However, as I have none registered (and an empty acc name shows in QCMA, as expected), it crashes because /keys/ + nothing is an invalid dir. Any solutions?

**Comment by ivdok** [comment]
Shit, probably should've edited out AID. Oh well, not that I was any interested in PSN.

**Comment by SilicaAndPina** [comment]
AID isnt anything important lmao.

Account Name: 

account name is blank >_>
its trying to open keys/<accountname> as a file
but its failing,

please do 
run.exe m 
for manual setup,
and enter something thats not blank for account name.

**Comment by SilicaAndPina** [comment]
closed for inactivity and probably solution
