### ISSUE TITLE
Psp clone naming errors

### ISSUE THREAD

**Issue by Duhjoker** [SilicaAndPina/psvimgtools-frontend#76]
Hi there

I downloaded and installed version 0.6 today and I'm having trouble cloning my psp games. If I use the random ID option it gives me the ascii error codec cant decode byte 0xc4 in position 8: ordinal not in range (128).

If I try to make up a name I get an error saying that I haven't used enough characters and it crashes. I'm using names of up to 12 characters letters and numerals.

my pc version is windows 10 64bit

**Comment by SilicaAndPina** [comment]
goddamn it i thought i fixed that shit.. >_> #BlameWindows xD

**Comment by Duhjoker** [comment]
Ok so i used a 9 character long name for the clone and i get the ascii error codec etc

**Comment by SilicaAndPina** [comment]
>_> b-but i fixed that shit allready arrg

**Comment by Duhjoker** [comment]
Wait.... do i need to re-download and install it?

**Comment by SilicaAndPina** [comment]
i dont think that will fix anything

**Comment by Duhjoker** [comment]
Ok so what do i do?

**Comment by Duhjoker** [comment]
Ok i tried downloading 3 different previous versions and i get the same ascii error code with each one.

**Comment by SilicaAndPina** [comment]
ill try fix it again. what game is this?

**Comment by Duhjoker** [comment]
LocoRoco

**Comment by Duhjoker** [comment]
Hi there 

Just to let you know.... i re-installed psvimgtools v 0.6 and still cannot name the cloned game

**Comment by Duhjoker** [comment]
Correction:::::

It does work if you use petz sadfle club demo. 

Thank you and a huge thank you for your work on the program

**Comment by SilicaAndPina** [comment]
it shouldnt break at all lol

**Comment by SilicaAndPina** [comment]
locoroco **maybe** working in 0.6.1 > _ >
