### ISSUE TITLE
i have Trouble about PSVimgtools 

### ISSUE THREAD

**Issue by Zeromaru19** [SilicaAndPina/psvimgtools-frontend#77]
i have Trouble 

--PSVIMGTOOLS-FRONTEND v0.6-\
| GUI BY SILICAANDPINA! |
| CLI BY YIFANLU / MOLECULE |
\-------------------------------/
Extracting CMBackup File
Checking for updates
Latest Version Is: v0.6
Current Version Is: v0.6
No Updates Available.
Updating: C:\Users\ThorTop\AppData\Roaming\psvimgtools-frontend/keydb.ini
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking For 64-Bit
Test OK!
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
Access is denied.
Error occurred while processing: .cmbackup.
Executing: ftype CmbackupFile="C:\Users\ThorTop\AppData\Roaming\psvimgtools-frontend\run.exe"
Access is denied.
Error occurred while processing: CmbackupFile.
Starting GUI
APP
Checking for Packed Backup..
Packed backup allredy exists. removing..
Packing backup..
Executing: psvimg-create.exe -m "/EXTRACTED/APP/VITASHELL/savedata.psvmd-dec" -K 33b412a57850234cd800ae885ee48845fe67db84eca0cacb0f904f19f6c0cdf6 "/EXTRACTED/APP/VITASHELL/savedata" "/APP/0706910764dd007b/VITASHELL/savedata"
metadata: No such file or directory
Executing: psvimg-create.exe -m "/EXTRACTED/APP/VITASHELL/license.psvmd-dec" -K 33b412a57850234cd800ae885ee48845fe67db84eca0cacb0f904f19f6c0cdf6 "/EXTRACTED/APP/VITASHELL/license" "/APP/0706910764dd007b/VITASHELL/license"
metadata: No such file or directory
Executing: psvimg-create.exe -m "/EXTRACTED/APP/VITASHELL/appmeta.psvmd-dec" -K 33b412a57850234cd800ae885ee48845fe67db84eca0cacb0f904f19f6c0cdf6 "/EXTRACTED/APP/VITASHELL/appmeta" "/APP/0706910764dd007b/VITASHELL/appmeta"
metadata: No such file or directory
Executing: psvimg-create.exe -m "/EXTRACTED/APP/VITASHELL/addcont.psvmd-dec" -K 33b412a57850234cd800ae885ee48845fe67db84eca0cacb0f904f19f6c0cdf6 "/EXTRACTED/APP/VITASHELL/addcont" "/APP/0706910764dd007b/VITASHELL/addcont"
metadata: No such file or directory
Executing: psvimg-create.exe -m "/EXTRACTED/APP/VITASHELL/patch.psvmd-dec" -K 33b412a57850234cd800ae885ee48845fe67db84eca0cacb0f904f19f6c0cdf6 "/EXTRACTED/APP/VITASHELL/patch" "/APP/0706910764dd007b/VITASHELL/patch"
metadata: No such file or directory
Executing: psvimg-create.exe -m "/EXTRACTED/APP/VITASHELL/app.psvmd-dec" -K 33b412a57850234cd800ae885ee48845fe67db84eca0cacb0f904f19f6c0cdf6 "/EXTRACTED/APP/VITASHELL/app" "/APP/0706910764dd007b/VITASHELL/app"
metadata: No such file or directory
Copying Folder: /EXTRACTED/APP/VITASHELL/sce_sys To: /APP/0706910764dd007b/VITASHELL/sce_sys

Please Help me

**Comment by SilicaAndPina** [comment]
its looking on your root folder?

**Comment by Zeromaru19** [comment]
Yes i know i have QCMA and i don't fix destination folder 

But i don't know why your program don't see  folder.

**Comment by SilicaAndPina** [comment]
idk. it read the config and saw the folder as nothing. not sure why. just fix it

**Comment by SilicaAndPina** [comment]
under backup mannager you can goto CMADIR, and enter a new directory.

you want to enter whats seen in BACKUPS And APPLICATIONS under QCMA.

**Comment by Zeromaru19** [comment]
Hmm I don't Understand.

Please Explain to me.

**Comment by SilicaAndPina** [comment]
its seeing your QCMA backups dir as blank "" so its trying to read it from your root directory,

this is an easy fix because you can change the directory that PSVIMGTOOLS tries to use to find your backups this option is under "Backup Mannager > CMA Dir" 
change it to where your QCMA backups are located.

**Comment by velvetmxo** [comment]
Hi, I am having issues with the latest PSVIMGTOOLS V0.6. there is no popup and the error i can capture via video since it closes quickly is 
KeyError: 'zRIF'
[1860] Failed to execute script run 

I can get the tools popup to work on the V0.5.2 without issues. the only problem is that vitashell is not available.

**Comment by SilicaAndPina** [comment]
Should be fixed in v0.6.1
