### ISSUE TITLE
Very very weird problem. 3 certain files cant be created for unknown reason

### ISSUE THREAD

**Issue by moogletimes** [SilicaAndPina/psvimgtools-frontend#80]
I have been working on this the whole day trying get Vitashell restored on my 3.65 Henkaku ps vita. But i can't get it to work no matter what.

It can't create these 3 files and i dont know why.
savedata.psvmd-dec
addcont.psvmd-dec
patch.psvmd-dec

/--PSVIMGTOOLS-FRONTEND v0.6-\
|  GUI BY SILICAANDPINA!        |
|  CLI BY YIFANLU / MOLECULE    |
\-------------------------------/
Extracting CMBackup File
Checking for updates
Latest Version Is: v0.6
Current Version Is: v0.6
No Updates Available.
Updating: C:\Users\adelm\AppData\Roaming\psvimgtools-frontend/keydb.ini
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking for C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED, /APP, /PGAME, /PSGAME, /PSM and /SYSTEM
Checking for EXTRACTED/APP
/EXTRACTED/APP Exists!
Checking for EXTRACTED/PGAME
/EXTRACTED/PGAME Exists!
Checking for EXTRACTED/PSGAME
/EXTRACTED/PSGAME Exists!
Checking for EXTRACTED/PSM
/EXTRACTED/PSM Exists!
Checking for EXTRACTED/SYSTEM
/EXTRACTED/SYSTEM Exists!
Check OK All Required Files Where Found/Created
Checking For 64-Bit
Running in 32-Bit mode.
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
.cmbackup=CmbackupFile
Executing: ftype CmbackupFile="C:\Users\adelm\AppData\Roaming\psvimgtools-frontend\run.exe"
CmbackupFile="C:\Users\adelm\AppData\Roaming\psvimgtools-frontend\run.exe"
Starting GUI
APP
Checking for Packed Backup..
Packed backup allredy exists. removing..
Packing backup..
Executing: psvimg-create.exe -m "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/savedata.psvmd-dec" -K 5ecec6531a50f5c2e3d9028070da27ec0709a16893a16ea3caa21f2eeab34e7a "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/savedata" "C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/savedata"
metadata: No such file or directory
Executing: psvimg-create.exe -m "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/license.psvmd-dec" -K 5ecec6531a50f5c2e3d9028070da27ec0709a16893a16ea3caa21f2eeab34e7a "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/license" "C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/license"
adding files for ux0:temp/game/VITASHELL/license/app/VITASHELL
packing file ux0:temp/game/VITASHELL/license/app/VITASHELL/6488b73b912a753a492e2714e9b38bc7.rif (200 bytes)...
created C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/license/license.psvimg (size: e40, content size: 200)
created C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/license/license.psvmd
Executing: psvimg-create.exe -m "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/appmeta.psvmd-dec" -K 5ecec6531a50f5c2e3d9028070da27ec0709a16893a16ea3caa21f2eeab34e7a "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/appmeta" "C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/appmeta"
adding files for ux0:temp/game/VITASHELL/appmeta/VITASHELL
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/ebootparam.bin (8000 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/icon0.png (8000 bytes)...
packing directory ux0:temp/game/VITASHELL/appmeta/VITASHELL/livearea...
packing directory ux0:temp/game/VITASHELL/appmeta/VITASHELL/livearea/contents...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/livearea/contents/bg.png (10000 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/livearea/contents/startup.png (8000 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/livearea/contents/template.xml (8000 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/param.sfo (8000 bytes)...
packing directory ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/files.db (1000 bytes)...
packing directory ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/2208b8f5.icv (800 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/51929436.icv (800 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/61d5979a.icv (800 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/6f0795f4.icv (18 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/857a9596.icv (800 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/99544ac4.icv (18 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/a5e7fdc6.icv (18 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/d84c6d48.icv (800 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/ed693b6a.icv (800 bytes)...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_pfs/icv.db/f3e66216.icv (800 bytes)...
packing directory ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_sys...
packing file ux0:temp/game/VITASHELL/appmeta/VITASHELL/sce_sys/sealedkey (8000 bytes)...
created C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/appmeta/appmeta.psvimg (size: 53b80, content size: 44848)
created C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/appmeta/appmeta.psvmd
Executing: psvimg-create.exe -m "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/addcont.psvmd-dec" -K 5ecec6531a50f5c2e3d9028070da27ec0709a16893a16ea3caa21f2eeab34e7a "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/addcont" "C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/addcont"
metadata: No such file or directory
Executing: psvimg-create.exe -m "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/patch.psvmd-dec" -K 5ecec6531a50f5c2e3d9028070da27ec0709a16893a16ea3caa21f2eeab34e7a "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/patch" "C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/patch"
metadata: No such file or directory
Executing: psvimg-create.exe -m "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/app.psvmd-dec" -K 5ecec6531a50f5c2e3d9028070da27ec0709a16893a16ea3caa21f2eeab34e7a "C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/app" "C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/app"
adding files for ux0:temp/game/VITASHELL/app/VITASHELL
packing file ux0:temp/game/VITASHELL/app/VITASHELL/eboot.bin (1c683e bytes)...
packing directory ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys...
packing file ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/icon0.png (9f8 bytes)...
packing directory ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/livearea...
packing directory ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/livearea/contents...
packing file ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/livearea/contents/bg.png (d31e bytes)...
packing file ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/livearea/contents/startup.png (1096 bytes)...
packing file ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/livearea/contents/template.xml (39c bytes)...
packing directory ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/package...
packing file ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/package/head.bin (430 bytes)...
packing file ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/package/work.bin (200 bytes)...
packing file ux0:temp/game/VITASHELL/app/VITASHELL/sce_sys/param.sfo (390 bytes)...
created C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/app/app.psvimg (size: 1df3a0, content size: 1d6346)
created C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/app/app.psvmd
Copying Folder: C:/Users/adelm/Desktop/for psvita/PS Vita/EXTRACTED/APP/VITASHELL/sce_sys To: C:/Users/adelm/Desktop/for psvita/PS Vita/APP/a2cc55da07e18a41/VITASHELL/sce_sys

I've tried different versions of everything and tried just changing folders and usb ports n nothing helps.
Really need to get this fixed otherwise i cant do anything :///

**Comment by SilicaAndPina** [comment]
what files?

**Comment by SilicaAndPina** [comment]
savedata.psvmd-dec
addcont.psvmd-dec
patch.psvmd-dec
will only be created if there is savedata/addcont/patch data backed up.

**Comment by moogletimes** [comment]
Ok Update:
I did try literally everything i could come up with. The thing that got it working for me is i just rebooted windows 10 into disable driver signature enforcement mode and i uninstalled basically qcma and the psvimgtools. Then i went and installed qcma only again but this time, i installed it into a folder on my desktop. Then i reconnected my psvita to pc and vitashell finally appeared in qcma. Now i got vitashell.

So my problem was with qcma not working correctly. Which is why nothing would appear there when i used it with psvimgtools. But installing qcma to another folder besides the regular "Program Files" folder fixed the problem. God i spend at least a solid 9 hours trying to figure this out.

I just naturally assumed that because i got that error there that something was wrong on that part. Sorry for wasting your time reading this XDD

**Comment by SilicaAndPina** [comment]
probably permission error, unless your admin you cant write to program files..

**Comment by moogletimes** [comment]
I am the sole user and have full admin privileges on my operating system. Always booted the application in admin mode anyway but it still wouldn't budge. Anyway i thank you for your insight on the subject. It helped me in troubleshooting and finally solving it.

**Comment by SilicaAndPina** [comment]
solved.
