### ISSUE TITLE
PSP/PS1 Whitelist Hack?

### ISSUE THREAD

**Issue by ABOhiccups** [SilicaAndPina/psvimgtools-frontend#84]
I did patch Whitelist with psvimgtools. Blacklisted PS Vita Games / Apps works! I try to run Sega Genesis Collection for PSP. I get a error message just like other Blacklisted Games. I don't know if this software patched PSP/PS1 Whitelist.

Well there be a update for that in the future?

**Comment by SilicaAndPina** [comment]
it cant patch psp whitlist only the whitelist 'v2' which is run in the app.db file
the reason why we cannot patch the psp or 'whitelist v1' is because its a file that is not backed up by CMA.
