### ISSUE TITLE
Unable to find Patches?

### ISSUE THREAD

**Issue by JaredStock20** [SilicaAndPina/psvimgtools-frontend#88]
(Hi! I'm super sorry if this is in the wrong place, I have used GitHub maybe twice in my life)

I have followed this video: https://youtu.be/ZMRLFnmwgYQ
But after clicking on Easy Installers, VHBL, and my account, the "Select Backup" page is empty.
I have redone this about six times, following a different video each time and I have gotten the exact same results.

I am a total noob when it comes to this stuff, so my only guess would be that it's looking in the wrong directory? The PSP demos are in:
 C:\Users\jared\OneDrive\Documents\PS Vita\PGAME\25354e606c621177
but the program is looking for:
/PGAME/25354e606c621177

Thanks for help in advance, I apologize for my ignorance.

**Comment by SilicaAndPina** [comment]
it appears the automatically find the location for qcma backups isnt working, its an easy fix though. just goto "Backup Manager > CMA Dir" and browse to teh correct location (C:\Users\jared\OneDrive\Documents\PS Vita)

or just open CMADir.txt in the install dir and write "C:\Users\jared\OneDrive\Documents\PS Vita" into it..
either should work.

**Comment by JaredStock20** [comment]
Worked great! Thanks a ton, I wish more developers on this site responded and helped as fast as you!

**Comment by JaredStock20** [comment]
Worked great! Thanks a ton, I wish more develops responded as fast as you!
